// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// getWEXP
Rcpp::List getWEXP(arma::mat data, arma::mat Y, int N, arma::mat RT_out, double predictTime, arma::vec resid_sco, double fitvar);
RcppExport SEXP survAccuracyMeasures_getWEXP(SEXP dataSEXP, SEXP YSEXP, SEXP NSEXP, SEXP RT_outSEXP, SEXP predictTimeSEXP, SEXP resid_scoSEXP, SEXP fitvarSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP );
        Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP );
        Rcpp::traits::input_parameter< int >::type N(NSEXP );
        Rcpp::traits::input_parameter< arma::mat >::type RT_out(RT_outSEXP );
        Rcpp::traits::input_parameter< double >::type predictTime(predictTimeSEXP );
        Rcpp::traits::input_parameter< arma::vec >::type resid_sco(resid_scoSEXP );
        Rcpp::traits::input_parameter< double >::type fitvar(fitvarSEXP );
        Rcpp::List __result = getWEXP(data, Y, N, RT_out, predictTime, resid_sco, fitvar);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// getWEXPcutoff
Rcpp::List getWEXPcutoff(arma::mat data, arma::mat subdata, arma::mat Y, arma::mat subY, int N, arma::mat RT_out, double predictTime, arma::vec resid_sco, double fitvar, arma::colvec cutoffs);
RcppExport SEXP survAccuracyMeasures_getWEXPcutoff(SEXP dataSEXP, SEXP subdataSEXP, SEXP YSEXP, SEXP subYSEXP, SEXP NSEXP, SEXP RT_outSEXP, SEXP predictTimeSEXP, SEXP resid_scoSEXP, SEXP fitvarSEXP, SEXP cutoffsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP );
        Rcpp::traits::input_parameter< arma::mat >::type subdata(subdataSEXP );
        Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP );
        Rcpp::traits::input_parameter< arma::mat >::type subY(subYSEXP );
        Rcpp::traits::input_parameter< int >::type N(NSEXP );
        Rcpp::traits::input_parameter< arma::mat >::type RT_out(RT_outSEXP );
        Rcpp::traits::input_parameter< double >::type predictTime(predictTimeSEXP );
        Rcpp::traits::input_parameter< arma::vec >::type resid_sco(resid_scoSEXP );
        Rcpp::traits::input_parameter< double >::type fitvar(fitvarSEXP );
        Rcpp::traits::input_parameter< arma::colvec >::type cutoffs(cutoffsSEXP );
        Rcpp::List __result = getWEXPcutoff(data, subdata, Y, subY, N, RT_out, predictTime, resid_sco, fitvar, cutoffs);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
