# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getWEXP <- function(data, Y, N, RT_out, predictTime, resid_sco, fitvar) {
    .Call('survAccuracyMeasures_getWEXP', PACKAGE = 'survAccuracyMeasures', data, Y, N, RT_out, predictTime, resid_sco, fitvar)
}

